libCubeEye: example Namespace Reference
example Namespace Reference
Classes
class _CubeEyeContext
class _CubeEyePythonSink
Functions
get_camera_state (state)
get_camera_error (error)
get_camera_result (result)
search_command (context, command_list)
select_command (context, command_list)
run_command (context, command_list)
stop_command (context, command_list)
set_command (context, command_list)
get_command (context, command_list)
help_command ()
main ()
Function Documentation
get_camera_error()
example.get_camera_error (error)
Referenced by example._CubeEyePythonSink.onCubeEyeCameraError().
get_camera_result()
example.get_camera_result (result)
Referenced by get_command(), run_command(), set_command(), and stop_command().
get_camera_state()
example.get_camera_state (state)
Referenced by example._CubeEyePythonSink.onCubeEyeCameraState().
get_command()
example.get_command (context, command_list)
References get_camera_result().
help_command()
example.help_command ()
Referenced by main().
main()
example.main ()
References help_command(), and main().
Referenced by main().
run_command()
example.run_command (context, command_list)
References get_camera_result().
search_command()
example.search_command (context, command_list)
select_command()
example.select_command (context, command_list)
set_command()
example.set_command (context, command_list)
References get_camera_result().
stop_command()
example.stop_command (context, command_list)
References get_camera_result().